# Generated by MPS

function runAntBuildTargets() {
if [[ "$OSTYPE" =~ ^msys ]]; then
  ANT_CP="$ANT_HOME/lib/ant.jar;$ANT_HOME/lib/ant-launcher.jar;$ANT_HOME/lib/ant-junit.jar;$ANT_HOME/lib/ant-junit4.jar;$ANT_HOME/lib/ant-junitlauncher.jar"
else
  ANT_CP="$ANT_HOME/lib/ant.jar:$ANT_HOME/lib/ant-launcher.jar:$ANT_HOME/lib/ant-junit.jar:$ANT_HOME/lib/ant-junit4.jar:$ANT_HOME/lib/ant-junitlauncher.jar"
fi
echo "mps.home/alef.home: ${MPS_HOME}"
echo "ant.home: ${ANT_HOME}"
echo "ant cp: ${ANT_CP}"
${JBR_HOME}/bin/java -cp "$ANT_CP" \
  -Dmps.home="$MPS_HOME" \
  -Dant.home="$ANT_HOME" \
  -Dmaven.settings="$MAVEN_SETTINGS" \
  -Dalef.home="$MPS_HOME" \
  -Drepo="$REPO_URL" \
  org.apache.tools.ant.Main -f build-alefproject.xml $1
}

if [ ! -z "${MAVEN_OPTS}" ]; then
  MAVEN_OPTIONS="${MAVEN_OPTS}"
elif [ ! -z "${MAVEN_ARGS}" ]; then
  MAVEN_OPTIONS="${MAVEN_ARGS}"
elif [ ! -z "${MAVEN_CONFIG}" ]; then
  MAVEN_OPTIONS="${MAVEN_CONFIG}"
fi
if [ ! -z "${MAVEN_OPTIONS}" ]; then
  for o in ${MAVEN_OPTIONS}; do
    if [ $o = "--settings" ]; then
      MAVEN_SETTINGS="settingsfile in next option";
      continue
    fi
    if [ ! -z "${MAVEN_SETTINGS}" ]; then
      MAVEN_SETTINGS=${o#\"}
      MAVEN_SETTINGS=${MAVEN_SETTINGS%\"}
    fi
  done
  echo "Using maven settings file:${MAVEN_SETTINGS}"
fi

if ! [ -z "${MPS_HOME}"]; then
  echo "MPS_HOME exists, so skipping bootstrapping"
  if [[ "$OSTYPE" =~ ^darwin ]]; then
    JBR_HOME="${MPS_HOME}/Contents/jbr/Contents/Home"
  else
    JBR_HOME="${MPS_HOME}/jbr"
  fi
  ANT_HOME="${MPS_HOME}/ant
  echo "Using JBR_HOME:${JBR_HOME}"
  runAntBuildTargets $@
  exit $?
fi

echo "Bootstrapping ant to run 'ant build-alefproject.xml $@'."

if [ -z "${REPO_URL:-}" ]; then
  REPO_URL=https://repo1.maven.org/maven2
fi
echo "Repository for bootstrapping:${REPO_URL}"

if [ -z "${ANT_HOME:-}" ]; then
  echo "ANT_HOME does not exist, downloading ant from bootstrapping repository."
  mkdir -p build/ant/lib
  curl --silent --output "build/ant/lib/ant.jar" ${REPO_URL}/org/apache/ant/ant/1.10.15/ant-1.10.15.jar
  curl --silent --output "build/ant/lib/ant-launcher.jar" ${REPO_URL}/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.jar
  ANT_HOME="build/ant"
else
    echo "Using existing ANT_HOME:${ANT_HOME}"
fi
if [ -z "${JAVA_HOME:-}" ]; then
  if command -v java > /dev/null; then
    JAVA_CMD="java"
  else
      echo "I need JRE 8 or newer to start Ant, but environment variable JAVA_HOME doesn't exist and java is not in your PATH. Please fix one of these problems and try again."
  fi
else
  echo "Using existing JAVA_HOME:${JAVA_HOME}"
  JAVA_CMD="${JAVA_HOME}/bin/java"
fi
echo "Using ${JAVA_CMD} and ${ANT_HOME} to bootstrap build-alefproject.xml."
"${JAVA_CMD}" -cp "$ANT_HOME/lib/*" -Drepo="$REPO_URL" -Dmaven.settings="$MAVEN_SETTINGS" org.apache.tools.ant.Main -f build-alefproject.xml bootstrap

# bootstrap target contract for each os: jbr in build/jbr; mps (with ant) in build/mps; variables with locations might be used in script calls
BUILD_DIR="$(pwd)/build"
JBR_HOME="${BUILD_DIR}/jbr"
MPS_HOME="${BUILD_DIR}/mps"
ANT_HOME="${MPS_HOME}/lib/ant"



runAntBuildTargets $@
